### PR TITLE
rewrite savesates

### PR DESCRIPTION
**Pull request by fr500**
It no longer uses a file as an intermediate buffer, it's almost there for netplay with 2 instances running on a core i5 2500k

### CODE REVIEW

**Comment by fr500** [comment]
It it's too ugly to have 2 functions I can rewrite it for... #ifdef __LIBRETRO or something

**Comment by fr500** [comment]
just to contrast, it's 90fps with rewind enabled granularity 1.
with the original method rewind doesn't work at all (or it is 0fps)

**Comment by fr500** [comment]
Hmm there's a leak somewhere :p

**Comment by loganmc10** [comment]
The mupen64plus-core folder is just a git clone of the upstream project, you can't make modifications in there.

I'd rather have some __LIBRETRO__ ifdefs and have it submitted to mupen64plus-core. I can submit it if you don't want to go through that process.

**Comment by fr500** [comment]
The whole function is different though... starting from the signature. Do you think they would merge?

**Comment by twinaphex** [comment]
You can submit it if you want, but honestly, I am not going to wait for that.

We are going to do a shallow fork of this repo right now and use that for our buildbot. We will merge this PR in there.

Whether you are successful or not in your endeavors to get this merged then does not become a blocking thing that we have to wait weeks or even months on.

**Comment by fr500** [comment]
@loganmc10 I don't want drama over this at all, I can do the steps to get it mergeable but I'm pretty sure they won't merge libretro stuff.

Let me know and I can look into it.

**Comment by twinaphex** [comment]
I will also emphasize that i don't want drama over this and that I appreciate loganmc10's efforts overall. I just massively disagree with this decision/stance taken right now, so until you figure this out with upstream, we'll do the shallow fork. We will try not to diverge too much from you so that it keeps being a 'shallow' fork.

**Comment by fr500** [comment]
Maybe they can provide the functionality, I opened an issue there
https://github.com/mupen64plus/mupen64plus-core/issues/228

**Pull request closed without merging**
