### PR TITLE
Make git hash like other cores and add CPPFLAGS

### PR DESCRIPTION
**Pull request by sergiobenrocha2**

### CODE REVIEW

**Comment by loganmc10** [comment]
Thanks for doing this. The only thing I don't really like is having the 2.5 in the version.

mupen64plus 2.5 was released April 2015, so I don't think it really accurately describes what the core is, since this tracks the git version of mupen64plus.

If anything, I would rather have it use the git version if it can, and if it can't, use the year-month it was compiled or something like that.

**Comment by sergiobenrocha2** [comment]
We need a version reference, even if it's old and inaccurate. Think about packages on linux (package devs needs to know what version it is). Many cores uses a base version which is not very accurate, like gen plus gx.

Maybe 2.5+ ?

**Comment by loganmc10** [comment]
I think "2.5-git" would be ok, and perhaps "2.5-$GIT_VERSION" if it avaliable, or something like that

**Comment by sergiobenrocha2** [comment]
Maybe "2.5-git $GIT_VERSION" ? The standard across cores, there's a space between the actual version and git hash

**Comment by loganmc10** [comment]
Can you just make $GIT_VERSION="git" if there is no hash? so "2.5 git", or "2.5 GIT_VERSION"

**Comment by sergiobenrocha2** [comment]
There ^

**Comment by loganmc10** [comment]
Perfect thanks

**Pull request merged**
