### PR TITLE
Fix cheat support on non-Linux desktop systems.

### LINKED ISSUE #148: Cheats not working on RetroPie
Hi,

I just updated to the newest commit 510c673 on RetroPie to use it with RetroArch.
I was hoping to get cheats to work, created a .cht with the codes from mupencheat.txt but it's not working. Even tried some other Gameshark codes, but these weren't working either. Am I doing something wrong?

Thanks in advance

### PR DESCRIPTION
**Pull request by ilag11111**
DO NOT ADD YET.  This is being submitted prior to any actual work being done so that the travis ci will cross-compile for me.  If @loganmc10 set things up correctly, the builds will appear somewhere in here: http://loganbuildbot.s3-website-us-east-1.amazonaws.com/

Will fix #148 once the other systems are debugged.

Below is a sample debug log.  This debug log was made by using the .cht file @loganmc10 provided in #148, on a verified dump of 007 Goldeneye [U], and a fully-working Linux x86_64 build.  Upon turning on cheat 0 in the list and applying changes, everything you see below should print to cmd, and one of the in-game save files should rename itself to 007 and have everything unlocked that can be unlocked.  Any discrepancies should be reported in this pull request.

RetroArch [INFO] :: Cheat: #0 [ON]: Enable All Levels & In-Built Cheat Menu
!!! - Cheat 0 name: cheat_0
!!! - Cheat part 0 found: 8006992E, decoded as 8006992E
!!! - Cheat part 1 found: FFFF, decoded as FFFF
!!! - Cheat part 2 found: 80069930, decoded as 80069930
!!! - Cheat part 3 found: FFFF, decoded as FFFF
!!! - Cheat part 4 found: 80069967, decoded as 80069967
!!! - Cheat part 5 found: FFFF, decoded as FFFF
!!! - Cheat part 6 found: 8006996C, decoded as 8006996C
!!! - Cheat part 7 found: FFFF, decoded as FFFF
!!! - Cheat part 8 found: 80069971, decoded as 80069971
!!! - Cheat part 9 found: FFFF, decoded as FFFF
!!! - Cheat part 10 found: 80069976, decoded as 80069976
!!! - Cheat part 11 found: FFFF, decoded as FFFF
!!! - Cheat part 12 found: 8006997B, decoded as 8006997B
!!! - Cheat part 13 found: FFFF, decoded as FFFF
!!! - Cheat part 14 found: 8006992F, decoded as 8006992F
!!! - Cheat part 15 found: FFFF, decoded as FFFF
!!! - Cheat part 16 found: 80069965, decoded as 80069965
!!! - Cheat part 17 found: FFFF, decoded as FFFF
!!! - Cheat part 18 found: 8006996A, decoded as 8006996A
!!! - Cheat part 19 found: FFFF, decoded as FFFF
!!! - Cheat part 20 found: 8006996F, decoded as 8006996F
!!! - Cheat part 21 found: FFFF, decoded as FFFF
!!! - Cheat part 22 found: 80069974, decoded as 80069974
!!! - Cheat part 23 found: FFFF, decoded as FFFF
!!! - Cheat part 24 found: 80069979, decoded as 80069979
!!! - Cheat part 25 found: FFFF, decoded as FFFF
!!! - Cheat Line 0: 8006992E FFFF
!!! - Cheat Line 1: 80069930 FFFF
!!! - Cheat Line 2: 80069967 FFFF
!!! - Cheat Line 3: 8006996C FFFF
!!! - Cheat Line 4: 80069971 FFFF
!!! - Cheat Line 5: 80069976 FFFF
!!! - Cheat Line 6: 8006997B FFFF
!!! - Cheat Line 7: 8006992F FFFF
!!! - Cheat Line 8: 80069965 FFFF
!!! - Cheat Line 9: 8006996A FFFF
!!! - Cheat Line 10: 8006996F FFFF
!!! - Cheat Line 11: 80069974 FFFF
!!! - Cheat Line 12: 80069979 FFFF
RetroArch [INFO] :: Applying cheat changes.

### CODE REVIEW

**Comment by loganmc10** [comment]
Sorry I realized that this actually won't work. Travis CI doesn't allow secret values (the key to my AWS account) to be used by PR's. A malicious PR could print the value of the key and have my Amazon key.

So anyway I had to revert that change. But I'll work on building this myself and uploading it to a Google Drive link or something

**Comment by loganmc10** [comment]
Ok here is a link to a win64 build with these changes:

https://drive.google.com/file/d/0B8iAuv3fmhb_MnM0RU9oOVMzS0E/view?usp=sharing

I won't have access to a Windows machine to test it until Monday unfortunately

**Comment by ilag11111** [comment]
Good news: After dusting off my old Windows 8 laptop, I have identified the problem.  And that problem is: I am stupid.  

So, the way my code works, cheat lines are first broken down into parts and second converted from string to int.  It worked great on my Linux x86_64 build because the int length is 64-bit.  But on all other targets, int is 32-bit.  That shouldn't be a problem, because 32-bits is enough to hold eight hexadecimal digits, which is the longest possible code length.  No, the problem is that I left the int signed.  This results in the string to int conversion function converting all codes into 7FFFFFFF, the maximum value of a signed 32-bit integer.  So I just made it unsigned, which has a maximum value of FFFFFFFF, eight full hexadecimal digits.

Once this build can be verified to function, I'll remove the debug printf lines and this will be ready to merge.

**Comment by loganmc10** [comment]
Ok here is a win64 build with that fix implemented:

https://drive.google.com/file/d/0B8iAuv3fmhb_aU45VjBGSmxIekU/view?usp=sharing

**Comment by ilag11111** [comment]
Nope, that didn't do it.  Looks like it's not just the type of variable, but the strtol function.  Evidently it doesn't actually convert a string into a long.  Let's hope that strtoul at least converts a string to an unsigned int.

**Comment by loganmc10** [comment]
Here is that build:

https://drive.google.com/open?id=0B8iAuv3fmhb_dkFoVlpienkzX0E

**Comment by ilag11111** [comment]
Bingo!  Now just give me one moment to remove the debug printf lines and we're good to go.

**Comment by loganmc10** [comment]
Closed via 8704447fa7b73fab90888f41c6e06c554ed1cca4

**Pull request closed without merging**
